language: csharp
dist: trusty
sudo: required
dotnet: 2.1.4

install:
 - sudo apt-get update -y
 - sudo apt-get install -y gnupg automake libtool
 - curl -sSL https://github.com/libuv/libuv/archive/v1.9.1.tar.gz | tar zxf - -C /tmp
 - (cd /tmp/libuv-1.9.1/ && ./autogen.sh && ./configure && make && sudo make install)
 - sudo ldconfig
 # for apache bench (ab)
 - sudo apt-get install -qq apache2-utils

matrix:
  fast_finish: true

  include:
    - os: linux
      mono: 5.4.1
    - os: linux
      mono: weekly
    - os: linux
      mono: latest
    - os: osx
      osx_image: xcode9.1
      mono: 5.4.1
    - os: osx
      osx_image: xcode9.1
      mono: latest

  allow_failures:
    - os: osx
    - mono: weekly
    - mono: latest

addons:
  apt:
    packages:
    - dotnet-sharedframework-microsoft.netcore.app-1.1.2

env:
  global:
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

script:
  - ./build.sh