image:
  - Visual Studio 2017
  - Visual Studio 2019

build_script:
  - cmd: build.cmd

init:
  - git config --global core.autocrlf input

environment:
  matrix:
   - arch: "x64"
     MSBUILD_PLATFORM: "Any CPU"
     PATH: '%USERPROFILE%\.nuget\packages\libuv\1.10.0\runtimes\win-x64\native;%PATH%'
 
artifacts:
 - path: build\pkg\*.nupkg 

test:  off

nuget:
  project_feed: true