image:
  - Visual Studio 2019
  
install:
- ps: Invoke-WebRequest -Uri 'https://dot.net/v1/dotnet-install.ps1' -UseBasicParsing -OutFile "$env:temp\dotnet-install.ps1"
- ps: '& $env:temp\dotnet-install.ps1 -Architecture x64 -Version 2.2.401 -InstallDir "$env:ProgramFiles\dotnet"'

build_script:
  - cmd: build.cmd

init:
  - git config --global core.autocrlf input

environment:
  matrix:
   - arch: "x64"
     MSBUILD_PLATFORM: "Any CPU"
     PATH: '%USERPROFILE%\.nuget\packages\libuv\1.10.0\runtimes\win-x64\native;%PATH%'
 
artifacts:
 - path: build\pkg\*.nupkg 

test:  off

nuget:
  project_feed: true
