os: Visual Studio 2017
init:
  - git config --global core.autocrlf input
version: 2.0.{build}

environment:
  matrix:
   - arch: "x86"
     MSBUILD_PLATFORM: x86
   - arch: "x64"
     MSBUILD_PLATFORM: "Any CPU"

install:
 - ps: Start-FileDownload 'https://github.com/libuv/libuv/archive/v1.11.0.zip'
 - cmd: |
        "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat"
        set GYP_MSVS_VERSION=2015
        7z x v1.11.0.zip & cd libuv-1.9.1 & vcbuild.bat %arch% shared debug
 - cmd: mkdir src\Suave.Tests\bin\Release\ & cp libuv-1.9.1\Debug\libuv.dll src\Suave.Tests\bin\Release\libuv.dll
 
build_script:
 - cmd: msbuild /t:Restore src/Suave.sln
 - cmd: msbuild /t:Restore src/Suave.netcore.sln
 - cmd: gem sources -r https://rubygems.org/
 - cmd: gem install bundler --no-ri --no-rdoc --source https://rubygems.org/
 - cmd: bundle install
 - cmd: bundle exec rake appveyor
 
artifacts:
 - path: build\pkg\*.nupkg 

test:  off

nuget:
  project_feed: true


